# Generated by Django 3.2.24 on 2024-02-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('year_of_publishing', models.CharField(max_length=40, verbose_name='Год публикации')),
                ('author', models.CharField(max_length=40, verbose_name='Автор')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
            ],
        ),
    ]
